
name: Android Build QA
on:
  push:
    branches: [ "qa" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk -t lib/main_qa.dart --flavor qa

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resident_mobile-qa-apk_${{ env.VERSION }}
          path: |
             build/app/outputs/flutter-apk/app-qa-release.apk
