name: iOS Build Demo
on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: pod cache clean --all
    - run: flutter pub get
    - name: Install Pods
      working-directory: ./ios
      run: arch -arm64 pod install
    - run: flutter build ipa -t lib/main_demo.dart --flavor demo --no-codesign
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resident_mobile-demo-ipa
        path: |
             build/ios/ipa/resident_mobile.ipa
