import 'package:flutter/material.dart';
import 'package:resident_app/features/whitelabel/data/models/whitelabel_model.dart';

abstract class ColorPalette {
  Color primaryBase = const Color(0xff0366dd);
  Color primary100 = const Color(0xfff5f9ff);
  Color primary200 = const Color(0xffe6f1ff);
  Color primary300 = const Color(0xffcde3fe);
  Color primary400 = const Color(0xffafd2fe);
  Color primary500 = const Color(0xff81b9fd);
  Color primary600 = const Color(0xff358ffc);
  Color primary700 = const Color(0xff025ac3);
  Color primary800 = const Color(0xff024392);
  Color primary900 = const Color(0xff002c61);
  Color primary1000 = const Color(0xff011e41);
  Color secondaryBase = const Color(0xff02aade);
  Color secondary100 = const Color(0xfff5fdff);
  Color secondary200 = const Color(0xffccf3ff);
  Color secondary300 = const Color(0xff99e6fe);
  Color secondary400 = const Color(0xff67dafe);
  Color secondary500 = const Color(0xff34cdfd);
  Color secondary600 = const Color(0xff02c1fc);
  Color secondary700 = const Color(0xff019aca);
  Color secondary800 = const Color(0xff017498);
  Color secondary900 = const Color(0xff004d65);
  Color secondary1000 = const Color(0xff002733);
  Color tertiaryBase = const Color(0xff1fde02);
  Color tertiary100 = const Color(0xfff7fef5);
  Color tertiary200 = const Color(0xffd4fbcf);
  Color tertiary300 = const Color(0xffaaf89f);
  Color tertiary400 = const Color(0xff80f56f);
  Color tertiary500 = const Color(0xff56f23f);
  Color tertiary600 = const Color(0xff2cef0f);
  Color tertiary700 = const Color(0xff23bf0c);
  Color tertiary800 = const Color(0xff1a8f09);
  Color tertiary900 = const Color(0xff115f06);
  Color tertiary1000 = const Color(0xff082f03);
  Color aquaAccent = const Color(0xff02decb);
  Color deepBlueAccent = const Color(0xff0220de);
  Color grayishBlueAccent = const Color(0xff315178);
  Color purpleAccent = const Color(0xff775ee0);
  Color magentaAccent = const Color(0xffde0299);
  Color chartreuseAccent = const Color(0xffb8de02);
  Color darkOliveAccent = const Color(0xff565e30);
  Color pumpkinAccent = const Color(0xffABF99F);
  Color goldAccent = const Color(0xffdebc02);
  Color surfaceContainerLowest = const Color(0xffffffff);
  Color surface = const Color(0xfff9fafa);
  Color surfaceBright = const Color(0xfff4f5f6);
  Color surfaceContainerLow = const Color(0xffeeeff1);
  Color surfaceContainer = const Color(0xffe9eaed);
  Color surfaceContainerHigh = const Color(0xffe3e5e8);
  Color surfaceContainerHighest = const Color(0xffdde0e3);
  Color surfaceDim = const Color(0xffd8dbdf);
  Color outlineVariant = const Color(0xffabb1ba);
  Color outline = const Color(0xff737d8b);
  Color onSurfaceVariant = const Color(0xff454b54);
  Color onSurface = const Color(0xff17191c);
  Color appBarBg = const Color(0xff035ac4);
  Color appBarTextIcon = const Color(0xfff5fdff);
  Color appBarAccent = const Color(0xff1fde02);
  Color badgeDot = const Color(0xff775ee0);
  Color badgeSingleChar = const Color(0xff775ee0);
  Color badgeSingleCharLabel = const Color(0xfff5fdff);
  Color badgeMultiChar = const Color(0xffaaf89f);
  Color badgeMultiCharLabel = const Color(0xff011e41);
  Color buttonPrimaryBg = const Color(0xff0366dd);
  Color buttonPrimaryDisabledBg = const Color(0xffe6f1ff);
  Color buttonPrimaryDisabledLabel = const Color(0xfff5fdff);
  Color buttonPrimaryOnTapBg = const Color(0xff024392);
  Color buttonPrimaryLabel = const Color(0xfff5fdff);
  Color buttonSecondaryBg = const Color(0xfff5f9ff);
  Color buttonSecondaryBorder = const Color(0xffe6f1ff);
  Color buttonSecondaryLabel = const Color(0xff035ac4);
  Color buttonSecondaryOnTapBg = const Color(0xffe6f1ff);
  Color buttonSecondaryDisabledBorder = const Color(0xffe6f1ff);
  Color buttonSecondaryDisabledLabel = const Color(0xffe6f1ff);
  Color buttonSecondaryDisabledBg = const Color(0xfff5f9ff);
  Color buttonSegmentedBorder = const Color(0xffabb1ba);
  Color buttonSegmentedSelectedBg = const Color(0xffccf3ff);
  Color buttonSegmentedUnselectedBg = const Color(0xffffffff);
  Color buttonSegmentedSelectedLabel = const Color(0xff002c61);
  Color buttonSegmentedUnselectedLabel = const Color(0xff002c61);
  Color buttonFabBg = const Color(0xff0366dd);
  Color buttonFabLabel = const Color(0xfff5fdff);
  Color cardBorder = const Color(0xffe9eaed);
  Color cardBg = const Color(0xffffffff);
  Color chipWipBorder = const Color(0xffd9d9d9);
  Color chipWipBorderBg = const Color(0xffd9d9d9);
  Color chipWipBorderLabel = const Color(0xffd9d9d9);
  Color chipWipFilledBg = const Color(0xffd9d9d9);
  Color chipWipFilledLabel = const Color(0xffd9d9d9);
  Color iconBaseTextIcon = const Color(0xff002c61);
  Color iconLinkTextIcon = const Color(0xff017498);
  Color iconSuccess = const Color(0xff51bf3f);
  Color inputFieldCheckboxCheck = const Color(0xfff5fdff);
  Color inputFieldCheckboxSelected = const Color(0xff025ac3);
  Color inputFieldCheckboxUnselectedBorder = const Color(0xffabb1ba);
  Color inputFieldCheckboxUnselected = const Color(0xffffffff);
  Color inputFieldInputBg = const Color(0xffffffff);
  Color inputFieldInputBorderNormal = const Color(0xffe3e5e8);
  Color inputFieldInputBorderFocus = const Color(0xff025ac3);
  Color inputFieldInputBorderSelected = const Color(0xff025ac3);
  Color inputFieldInputBorderWarning = const Color(0xffd30651);
  Color inputFieldRadioSelected = const Color(0xff025ac3);
  Color inputFieldRadioUnselected = const Color(0xffabb1ba);
  Color inputFieldSwitchSliderOn = const Color(0xfff5fdff);
  Color inputFieldSwitchTrackOn = const Color(0xff025ac3);
  Color inputFieldSwitchSliderOff = const Color(0xff737d8b);
  Color inputFieldSwitchTrackOff = const Color(0xffe9eaed);
  Color layoutSurfaceBase = const Color(0xffffffff);
  Color layoutSurfaceRaised = const Color(0xffffffff);
  Color layoutScrimSurface = const Color(0xffcde3fe);
  Color layoutSkeletonLoading = const Color(0xffe9eaed);
  Color navigationDrawerIconText = const Color(0xff035ac4);
  Color navigationDrawerBg = const Color(0xffffffff);
  Color navigationDrawerSubmenuBg = const Color(0xfff5fdff);
  Color snackbarSuccess = const Color(0xffaaf89f);
  Color snackbarSuccessLabel = const Color(0xff002c61);
  Color statusBarBg = const Color(0xff025ac3);
  Color statusBarTextIcon = const Color(0xfff5fdff);
  Color textBase = const Color(0xff002c61);
  Color textMuted = const Color(0xff737d8c);
  Color textLink = const Color(0xff017498);
  Color textBrand = const Color(0xff0366dd);
  Color warningWarning = const Color(0xffd30651);
  Color warningOnWarning = const Color(0xfffffafc);
  Color warningWarningContainer = const Color(0xffffe0ec);
  Color warningOnWarningContainer = const Color(0xff3d0018);

  ///
  /// Extra Colors
  ///
  //
  Color grassColor = const Color(0xFFE9F2DF);

  ColorPalette();

  ColorPalette.fromModel(WhitelabelModel model);
}
