name: Flutter Android Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Get current version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Increment build number
        id: increment
        run: |
          CURRENT_VERSION=$(echo "${{ steps.version.outputs.current_version }}" | sed 's/^"//;s/"$//')
          MAJOR_MINOR=$(echo $CURRENT_VERSION | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $CURRENT_VERSION | cut -d'+' -f2)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          NEW_VERSION="${MAJOR_MINOR}+${NEW_BUILD_NUMBER}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
      - name: Update version in pubspec.yaml
        run: |
          sed -i "s/version: .*/version: ${{ steps.increment.outputs.new_version }}/" pubspec.yaml
          
      - name: Run tests
        run: flutter test
        
      - name: Build AAB
        run: flutter build appbundle --release -t lib/main_qa.dart --flavor qa
        
      - name: Upload AAB to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/bundle/release/app-release.aab

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and push version update
        run: |
          git add pubspec.yaml
          git commit -m "Bump version to ${{ steps.increment.outputs.new_version }} [skip ci]"
          git push
