name: Android Check
on:
  pull_request:
    branches: [ "master", "dev" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: 'stable'

      - name: Decode And Store Google Services Config
        env:
          ANDROID_GOOGLE_SERVICES_CONFIG_BASE64: '${{ secrets.ANDROID_GOOGLE_SERVICES_CONFIG_BASE64 }}'
        run: |
          android_qa_path=android/app/src/qa
          mkdir -p $android_qa_path
          echo $ANDROID_GOOGLE_SERVICES_CONFIG_BASE64 | base64 --decode > $android_qa_path/google-services.json

      - name: Decode And Store Flutter Firebase Options
        env:
          FLUTTER_FIREBASE_OPTIONS_BASE64: '${{ secrets.FLUTTER_FIREBASE_OPTIONS_BASE64 }}'
        run: |
          echo $FLUTTER_FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options_qa.dart

      - run: flutter pub get

      - name: Run Tests
        run: flutter test

      - run: flutter build appbundle -t lib/main_qa.dart --flavor qa --debug