name: iOS Check
on:
  pull_request:
    branches: [ "master", "dev" ]

  workflow_dispatch:
jobs:
  build:
    name: iOS build process
    environment: qa
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: pod cache clean --all

    - name: List available Xcode versions
      run: |
        sudo xcode-select -p
        ls -l /Applications/Xcode*.app

    # Note, this is a workaround for the issue with the default Xcode version is 15.4 and we need to use 16.x for the new iOS requirement. See https://manageamerica.atlassian.net/browse/RMST-1822
    - name: Select the Xcode version we want to use.
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

    - name: Verify Xcode version
      run: xcodebuild -version

    - name: Decode And Store Google Services Info.Plist Config
      env:
        IOS_GOOGLE_SERVICES_INFO_PLIST_CONFIG_BASE64: '${{ secrets.IOS_GOOGLE_SERVICES_INFO_PLIST_CONFIG_BASE64 }}'
      run: |
        ios_qa_path=ios/Runner/firebase/qa
        mkdir -p $ios_qa_path
        echo $IOS_GOOGLE_SERVICES_INFO_PLIST_CONFIG_BASE64 | base64 --decode > $ios_qa_path/GoogleService-info.plist

    - name: Decode And Store Flutter Firebase Options
      env:
        FLUTTER_FIREBASE_OPTIONS_BASE64: '${{ secrets.FLUTTER_FIREBASE_OPTIONS_BASE64 }}'
      run: |
        echo $FLUTTER_FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options_qa.dart

    - run: flutter pub get

    - name: Run Tests
      run: flutter test

    - name: Install Pods
      working-directory: ./ios
      run: arch -arm64 pod install

    - run: flutter build ios -t lib/main_qa.dart --flavor qa --no-codesign
